jobs:
  mail_on_push:
    runs-on: ubuntu-latest
  steps:
    - name: Send mail
  uses: dawidd6/action-send-mail@v3
with:
  server_address: smtp.gmail.com
  server_port: 465
  username: ${{secrets.MAIL_USERNAME}}
  password: ${{secrets.MAIL_PASSWORD}}
subject: Test ${{github.event.head_commit.message}}
body: Test ${{github.repository}} ${{github.event.pusher.name}}
to: aloe322@gmail.com
from: Github actions
